CREATE DATABASE BDM_PROYECTO;

USE BDM_PROYECTO;

CREATE TABLE USUARIO
(
	ID_USUARIO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(50),
    CORREO VARCHAR(30),
    ROL ENUM('CLIENTE', 'VENDEDOR', 'ADMINISTRADOR'),
    PASS_WORD VARCHAR(20)
);
ALTER TABLE USUARIO
ADD IMAGEN LONGBLOB, ADD ACTIVO BOOLEAN; 

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    GENERO ENUM('HOMBRE', 'MUJER', 'OTRO'),
    BIRTH_DAY DATE,
    TELEFONO BIGINT,
    DIRECCION VARCHAR(100),
    IS_PUBLIC BOOLEAN, 
    ID_USUARIO INT UNSIGNED,
    ID_METODO INT UNSIGNED,
    
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY(ID_METODO) REFERENCES METODO_PAGO(ID_METODO)
);

CREATE TABLE VENDEDOR
(
	ID_VENDEDOR INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    GENERO ENUM('HOMBRE', 'MUJER', 'OTRO'),
    BIRTH_DAY DATE,
    TELEFONO BIGINT,
    DIRECCION VARCHAR(100),
    IS_PUBLIC BIT, 
    ID_USUARIO INT UNSIGNED,
    
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ADMINISTRADOR
(
	ID_ADMIN INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    GENERO ENUM('HOMBRE', 'MUJER', 'OTRO'),
    BIRTH_DAY DATE,
    TELEFONO BIGINT,
    DIRECCION VARCHAR(100),
    IS_PUBLIC BIT, 
    ID_USUARIO INT UNSIGNED,
    
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PRODUCTOS
(
	ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VAL_PROM DECIMAL(3, 1),
    CANTIDAD INT,
    PRECIO DECIMAL(5, 2),
    NOMBRE VARCHAR(100),
    DESCRIPCION CHAR,
	ID_COMENTARIO INT UNSIGNED,
    ID_ADMIN INT UNSIGNED, 
    ID_VENDEDOR INT UNSIGNED,
    
    FOREIGN KEY(ID_COMENTARIO) REFERENCES COMENTARIOS(ID_COMENTARIO),
    FOREIGN KEY(ID_ADMIN) REFERENCES ADMINISTRADOR(ID_ADMIN),
    FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

ALTER TABLE PRODUCTOS
ADD IMAGEN LONGBLOB;

CREATE TABLE VENTA
(
	ID_VENTA INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_VENDEDOR INT UNSIGNED,
    ID_CLIENTE INT UNSIGNED,
    ID_METODO INT UNSIGNED, 
    FECHA DATETIME, 
    TOTAL DECIMAL(5, 2),
    VALORACION SMALLINT COMMENT 'SOLO SE PUEDE VALORAR DEL 1 AL 10',
    
    
	FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_METODO) REFERENCES METODO_PAGO(ID_METODO)
);

CREATE TABLE VENTA_DETALLE
(
	ID_VENTA INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    PRECIO DECIMAL(5, 2),
    CANTIDAD INT,
    CANT_EXIST INT,
    
    FOREIGN KEY(ID_VENTA) REFERENCES VENTA(ID_VENTA),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE COTIZACION
(
	ID_CLIENTE INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    FECHA DATETIME, 
    CANTDAD INT, 
    VALORACION SMALLINT,
    NEW_PRICE DECIMAL(5, 2),
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE CATEGORIAS
(
	ID_CATEGORIA INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    DESCRIPCION CHAR,
    NOMBRE VARCHAR(20),
    ID_ADMIN INT UNSIGNED,
    ID_VENDEDOR INT UNSIGNED,
    
    FOREIGN KEY(ID_ADMIN) REFERENCES ADMINISTRADOR(ID_ADMIN),
    FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

CREATE TABLE MULTI_CATEGORIAS
(
	ID_CATEGORIA INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    
    FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE LISTAS
(
	ID_LISTA INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION CHAR, 
    IMAGENES BLOB,
    IS_PUBLIC BIT,
    ID_CLIENTE INT UNSIGNED,
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE CARRITO
(
	ID_CLIENTE INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    CANT_PROD INT, 
    FECHA DATETIME,
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE LISTA_PRODUCTO
(
	ID_LISTA INT UNSIGNED,
    ID_PRODUCTO INT UNSIGNED,
    
    FOREIGN KEY(ID_LISTA) REFERENCES LISTAS(ID_LISTA),
    FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE COMENTARIOS
(
	ID_COMENTARIO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FECHA DATETIME, 
    CONTENIDO CHAR,
    ID_CLIENTE INT UNSIGNED,
    ID_VENDEDOR INT UNSIGNED,
    
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

CREATE TABLE METODO_PAGO
(
	ID_METODO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TARJETA INT,
    PAYPAL VARCHAR(25)
);