DELIMITER /
CREATE PROCEDURE SP_PERFIL_C (
IN IDC INT UNSIGNED
 )
BEGIN
	SELECT * FROM V_PERFIL WHERE ID_USUARIO=IDC;
END/

DROP PROCEDURE SP_PERFIL_C;

CALL PROCEDURE SP_PERFIL_C(1);

CREATE VIEW V_PERFIL
AS SELECT U.ID_USUARIO, C.NOMBRE, C.GENERO, C.BIRTH_DAY, U.IMAGEN, U.ROL, U.USER_NAME, U.CORREO
FROM CLIENTE AS C
JOIN USUARIO AS U
ON C.ID_USUARIO = U.ID_USUARIO;

SELECT * FROM V_PERFIL WHERE ID_USUARIO=1;

DROP VIEW V_PERFIL;


DELIMITER /
CREATE PROCEDURE REGISTRAR_USUARIO (
 IN USER_NAME_P VARCHAR(50),
 IN CORREO_P VARCHAR(30),
 IN ROL_P ENUM('CLIENTE', 'VENDEDOR', 'ADMINISTRADOR'),
 IN PASS_WORD_P VARCHAR(20),
 IN NOMBRE_P VARCHAR(100),
 IN GENERO_P ENUM('HOMBRE', 'MUJER', 'OTRO'),
 IN BIRTH_DAY_P DATE,
 IN TELEFONO_P BIGINT,
 IN DIRECCION_P VARCHAR(100),
 IN IS_PUBLIC_P BOOLEAN,
 IN IMAGEN_P LONGBLOB
 )
BEGIN
	DECLARE IDC INT;
    INSERT INTO USUARIO(USER_NAME, CORREO, PASS_WORD, ROL, IMAGEN)
    VALUES(USER_NAME_P, CORREO_P, PASS_WORD_P, ROL_P, IMAGEN_P);
    SET IDC = (SELECT ID_USUARIO FROM USUARIO ORDER BY ID_USUARIO DESC LIMIT 1);
    INSERT INTO CLIENTE(ID_USUARIO, NOMBRE, BIRTH_DAY, GENERO, 
    TELEFONO, DIRECCION, IS_PUBLIC)
    VALUES(IDC, NOMBRE_P, BIRTH_DAY_P, GENERO_P, TELEFONO_P, 
    DIRECCION_P, IS_PUBLIC_P);
END/

CALL REGISTRAR_USUARIO('JUANES', 'juan_xd@gmail.com', 1, '1234_Root', 
'JUANITE PEREZ', 3, '2000-08-14', 1123456789, 'LACASADEMICKEYMOUSE', TRUE, NULL);

DELIMITER /
CREATE PROCEDURE EDITAR_USUARIO (
 IN ID_USUARIO_P INT,
 IN USER_NAME_P VARCHAR(50),
 IN CORREO_P VARCHAR(30),
 IN PASS_WORD_P VARCHAR(20),
 IN ID_CLIENTE_P INT,
 IN NOMBRE_P VARCHAR(100),
 IN GENERO_P ENUM('HOMBRE', 'MUJER', 'OTRO'),
 IN BIRTH_DAY_P DATE,
 IN TELEFONO_P BIGINT,
 IN DIRECCION_P VARCHAR(100),
 IN IS_PUBLIC_P BOOLEAN, 
 IN IMAGEN_P LONGBLOB)
BEGIN
	UPDATE USUARIO SET USER_NAME=USER_NAME_P, CORREO=CORREO_P, 
    PASS_WORD=PASS_WORD_P, IMAGEN=IMAGEN_P WHERE ID_USUARIO=ID_USUARIO_P;
    UPDATE CLIENTE SET NOMBRE=NOMBRE_P, BIRTH_DAY=BIRTH_DAY_P, GENERO=GENERO_P, 
    TELEFONO=TELEFONO_P, DIRECCION=DIRECCION_P, IS_PUBLIC=IS_PUBLIC_P WHERE ID_CLIENTE=ID_CLIENTE_P;
END/


CALL EDITAR_USUARIO(1, 'JUAN', 'ernoe.med@gmail.com', '1234_Root', 1,'JUAN JAIME', 3, '2001-08-14', 
1123456789, 'LACASADEMICKEYMOUSE', FALSE, NULL);

SELECT * FROM USUARIO;

DELIMITER $$
CREATE PROCEDURE ELIMINAR_USUARIO (IN ID_USUARIO_P INT, IN ID_ROL_P INT, 
IN ROL_P ENUM('CLIENTE', 'VENDEDOR'))
BEGIN
IF ROL_P=1
THEN
    DELETE FROM CLIENTE WHERE ID_CLIENTE=ID_ROL_P;
    DELETE FROM USUARIO WHERE ID_USUARIO=ID_USUARIO_P;
END IF;
IF ROL_P=2
THEN
    DELETE FROM VENDEDOR WHERE ID_VENDEDOR=ID_ROL_P;
    DELETE FROM USUARIO WHERE ID_USUARIO=ID_USUARIO_P;
END IF;
END $$

CALL ELIMINAR_USUARIO(2, 2, 1);

DELIMITER /
CREATE PROCEDURE NUEVA_CATEGORIA (
	IN ID_CATEGORIA_P INT,
	IN NOMBRE_P VARCHAR(50),
    IN DESCRIPCION_P VARCHAR(200),
    IN ID_VENDEDOR_P INT,
    IN ID_ADMINISTRADOR_P INT
    )
BEGIN
    INSERT INTO VATEGORIAS(ID_CATEGORIA, NOMBRE, DESCRIPCION, ID_VENDEDOR, ID_ADMINISTRADOR)
    VALUES(1, NOMBRE_P, DESCRIPCION_P, ID_VENDEDOR_P, ID_ADMINISTRADOR_P);
END/

DELIMITER /
CREATE PROCEDURE OBTENER_CATEGORIAS()
BEGIN
	SELECT ID_CATEGORIAS, NOMBRE
    FROM CATEGORIAS;
END/
